on:
  push:
     branches:
       - main
  schedule:
    - cron:  '0 3 * * *'

name: businesscycles-render

jobs:
  bookdown:
    name: renderbook
    #runs-on: macOS-latest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Environment Variables
        run: echo FRED_API=${{ secrets.APIKEY }} >> .env
      - name: Render Book from Action
        uses: ckrusemd/jupyterbook-action@v0.15
      - uses: actions/upload-artifact@v1
        with:
          name: _book
          path: _book/

  checkout-and-deploy:
    runs-on: ubuntu-latest
    needs: bookdown
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Download artifact
      uses: actions/download-artifact@v2
      with:
        name: _book # optional
        path: _book # optional
    - name: Deploy to GitHub Pages
      uses: Cecilapp/GitHub-Pages-deploy@v3
      with:
        build_dir: _book/
        email: ${{ secrets.EMAIL }}  #optional
        jekyll: no                     # optional
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        EMAIL: ${{ secrets.EMAIL }}
        BUILD_DIR: _book/
